# -*- coding: utf-8 -*-
# Inhoud van interieurontwerpersgids.be: tien hoofdstukken over het vak van de interieurontwerper.

SITE = {
    "domain": "interieurontwerpersgids.be",
    "url": "https://interieurontwerpersgids.be",
    "name": "Interieurontwerpersgids",
    "tagline": "Hoe een interieurontwerp tot stand komt",
    "description": "Gids over het werk van de interieurontwerper: van briefing en plattegrond tot keuken, badkamer, kleurplan, verlichting, montage en de laatste accessoires.",
    "email": "info@interieurontwerpersgids.be",
}

# Elk hoofdstuk: fase in het ontwerpproces, artikel in stappen, een fiche en een verwijzing.
CHAPTERS = [
    {
        "slug": "briefing-en-plattegrond",
        "nr": "01",
        "fase": "Voorbereiding",
        "title": "Briefing en plattegrond",
        "h1": "Briefing en plattegrond: waar elk interieurontwerp begint",
        "meta": "Hoe een interieurontwerper een opdracht start: de briefing, de opmeting, de plattegrond op schaal en de eerste zonering, met de vragen die erbij horen.",
        "intro": "Een interieurontwerp begint niet bij een moodboard maar bij twee documenten: een briefing die vastlegt wat de bewoners nodig hebben, en een plattegrond op schaal die vastlegt wat de ruimte toelaat. Alles wat daarna komt, van keuken tot kussen, wordt aan die twee documenten getoetst.",
        "fiche": [("Fase", "Voorbereiding, voor er iets gekozen wordt"), ("Resultaat", "Briefing, opmeting, plattegrond 1:50, zonering"), ("Wie", "Ontwerper samen met de bewoners"), ("Valkuil", "Beginnen met inspiratiebeelden voor de maten bekend zijn")],
        "steps": [
            ("De briefing",
             ["Een briefing is een lijst van antwoorden. Wie woont er en hoe lang nog in deze samenstelling? Wie kookt, wie werkt thuis, wie ontvangt? Welke ruimte wordt nu niet gebruikt en waarom? Wat moet weg, wat moet blijven omdat het dierbaar is? Welk budget is er en welke termijn? Een ontwerper stelt die vragen in een eerste gesprek en schrijft de antwoorden uit, zodat iedereen later hetzelfde document heeft.",
              "Hoe concreter de briefing, hoe minder discussie achteraf. 'Meer licht in de leefruimte' is een wens. 'Een leeshoek bij het raam op het zuiden, met plaats voor twee mensen en een lamp' is een ontwerpopgave."]),
            ("De opmeting",
             ["Een bestaande plattegrond van de architect is een begin, maar zelden juist tot op de centimeter. Een ontwerper meet zelf: muren, hoogtes, ramen met borstwering en bovenkant, deuren met draairichting, radiatoren, stopcontacten, lichtpunten, afvoeren en de plaats van de meterkast. Ook de hoogte van de vensterbank en de dikte van de muren worden genoteerd, want daar hangt later een kast of een gordijnrail aan."]),
            ("De plattegrond op schaal",
             ["Alle maten komen op een tekening op schaal 1:50, op papier of in een tekenprogramma. Op die schaal is een centimeter op papier een halve meter in het echt, groot genoeg om een zetel van 2,4 meter en een looproute van 80 centimeter uit elkaar te houden. Op de plattegrond staan ook de lichtinval per dagdeel en de zichtlijnen: wat ziet iemand bij het binnenkomen, wat ziet iemand vanuit de zetel?"]),
            ("Zonering",
             ["Met de briefing naast de plattegrond worden zones getekend: koken, eten, zitten, werken, slapen, bergen. Zones die bij elkaar horen, liggen naast elkaar; zones die elkaar storen, zoals werken en televisie kijken, liggen uit elkaar of worden gescheiden door een kast of een niveauverschil. Pas als de zonering klopt, worden er meubels getekend. Een zetel die op de verkeerde plek staat, is niet te redden met een mooie stof."]),
            ("Wanneer een ontwerper inschakelen",
             ["Voor een enkele kamer kan een bewoner deze stappen zelf zetten. Bij een verbouwing waarbij muren verplaatst worden, een keuken en een badkamer tegelijk vernieuwd worden of een woning volledig heringericht wordt, loont een interieurontwerper of interieurarchitect. Die laatste titel is in België beschermd en gekoppeld aan een opleiding en een register, wat van belang is zodra er structurele ingrepen bij komen kijken."]),
        ],
        "partner": None,
    },
    {
        "slug": "keukenontwerp",
        "nr": "02",
        "fase": "Vaste inrichting",
        "title": "Keukenontwerp",
        "h1": "Keukenontwerp: de werkdriehoek, de opstelling en het maatwerk",
        "meta": "Hoe een interieurontwerper een keuken opzet: de werkdriehoek, de opstellingen, werkhoogte, opbergruimte, toestellen en de rol van de keukenbouwer.",
        "intro": "De keuken is het duurste en meest technische onderdeel van een interieur, en de plek waar een ontwerpfout het langst blijft steken. Een ontwerper tekent de keuken daarom als eerste vaste element in de plattegrond, nog voor de zithoek, omdat water, afvoer en elektriciteit de plaats van de keuken grotendeels vastleggen.",
        "fiche": [("Fase", "Vaste inrichting, na de plattegrond"), ("Resultaat", "Opstelling, werkhoogte, toestellenlijst, aansluitplan"), ("Wie", "Ontwerper en keukenbouwer"), ("Valkuil", "Toestellen kiezen voor de opstelling vastligt")],
        "steps": [
            ("De werkdriehoek",
             ["Koelkast, spoelbak en kookplaat vormen de drie hoeken van de werkdriehoek. De afstanden ertussen liggen bij voorkeur tussen 1,2 en 2,7 meter, met een totale omtrek van hoogstens ongeveer 8 meter. Kleiner wordt krap, groter wordt lopen. Tussen kookplaat en spoelbak hoort minstens 60 centimeter werkblad, aan weerszijden van de kookplaat minstens 30 centimeter."]),
            ("Opstellingen",
             ["Een rechte keuken past in een smalle ruimte maar geeft weinig werkblad. Een parallelkeuken met twee wanden tegenover elkaar is de meest efficiënte voor wie veel kookt. Een L-vorm opent de keuken naar de leefruimte. Een U-vorm biedt het meeste werkblad en opbergruimte. Een eiland vraagt minstens 1 meter, liever 1,2 meter, vrije ruimte rondom en een ruimte van minstens 4 bij 4 meter om niet te knellen."]),
            ("Hoogtes en ergonomie",
             ["De standaardwerkhoogte van rond 90 centimeter past bij een lichaamslengte van ongeveer 1,70 meter. Een vuistregel is de hoogte van de elleboog min 10 tot 15 centimeter. Wie groter is, kiest een hoger werkblad of een dikkere plint. Een oven op ooghoogte in een hoge kast spaart de rug, een vaatwasser verhoogd ook. Bovenkasten beginnen minstens 50 centimeter boven het werkblad."]),
            ("Opbergen en toestellen",
             ["Lades zijn praktischer dan deuren in onderkasten, omdat de inhoud naar voren komt in plaats van dat iemand erin moet kruipen. Hoekkasten krijgen een draaiplateau of een uittreksysteem. De toestellen worden pas gekozen als de opstelling vastligt, want een breed fornuis of een Amerikaanse koelkast verandert de hele maatvoering. Elk toestel krijgt op het aansluitplan een eigen stopcontact of aansluiting, met extra stopcontacten boven het werkblad om de 60 tot 90 centimeter."]),
            ("Werken met een keukenbouwer",
             ["Een ontwerper tekent de opstelling en de maatvoering; de keukenbouwer vertaalt dat naar kasten, fronten, werkblad en montage. Dovy Keukens, een Belgische keukenfabrikant uit Roeselare met een eigen productie en toonzalen, met een site op https://www.dovykeukens.be/, werkt met maatwerk en een 3D-ontwerp van de keuken, wat aansluit op de werkwijze uit dit hoofdstuk: eerst de opstelling, dan de toestellen, dan de afwerking."]),
        ],
        "partner": {"name": "Dovy Keukens", "url": "https://www.dovykeukens.be/", "anchor": "Dovy Keukens",
                    "blurb": "Belgische keukenfabrikant met eigen productie, maatwerk en 3D-ontwerp."},
    },
    {
        "slug": "badkamerontwerp",
        "nr": "03",
        "fase": "Vaste inrichting",
        "title": "Badkamerontwerp",
        "h1": "Badkamerontwerp: zones, maten en materialen in een natte ruimte",
        "meta": "Hoe een interieurontwerper een badkamer indeelt: de vier zones, minimale maten rond douche, bad en wastafel, ventilatie, waterdichting en materiaalkeuze.",
        "intro": "Een badkamer is klein, nat en vol techniek. Elke centimeter telt en elke fout in de afdichting komt jaren later terug als een vochtplek. Een ontwerper behandelt de badkamer als een technisch plan met een esthetische laag erover, in die volgorde.",
        "fiche": [("Fase", "Vaste inrichting, samen met de keuken"), ("Resultaat", "Indeling, leidingplan, materiaalstaat, ventilatie"), ("Wie", "Ontwerper, loodgieter, tegelzetter"), ("Valkuil", "Een inloopdouche zonder voldoende afschot en afdichting")],
        "steps": [
            ("Vier zones",
             ["Een badkamer heeft vier functies: wassen aan de wastafel, douchen of baden, toilet en bergen. In een kleine badkamer liggen ze op een rij langs een muur, wat leidingwerk bespaart. In een grotere badkamer krijgt de douche een eigen hoek en het toilet een plek uit het zicht van de deur. Een dubbele wastafel vraagt minstens 1,2 meter breedte, een enkele 60 tot 90 centimeter."]),
            ("Minimale maten",
             ["Een douche is minstens 90 bij 90 centimeter, comfortabel vanaf 100 bij 120. Een inloopdouche zonder deur heeft een lengte van minstens 1,2 meter nodig om spatwater binnen te houden. Voor een bad is 170 bij 75 centimeter gangbaar. Voor een toilet is 90 centimeter breedte en 120 centimeter diepte het minimum. Voor de wastafel geldt 70 centimeter vrije ruimte ervoor. De wastafel zelf komt op 85 tot 90 centimeter hoogte."]),
            ("Water, afvoer en ventilatie",
             ["Afvoeren vragen een afschot van minstens 1 centimeter per meter. Een douchevloer op gelijk niveau met de rest van de badkamer, de zogenaamde inloopdouche, vraagt een opbouwhoogte die in een bestaande vloer niet altijd beschikbaar is; een ontwerper controleert dat voor er iets getekend wordt. Ventilatie is geen optie maar een vereiste: een afzuiging die na het douchen nog een kwartier doorloopt, voorkomt schimmel op voegen en plafond."]),
            ("Waterdichting en materiaal",
             ["Onder de tegels in de douchezone komt een waterdichte laag met kimband in alle hoeken, tot minstens 2 meter hoog rond de douche. Op de vloer horen tegels met antislipklasse R10 of hoger. Grote tegels beperken het aantal voegen en dus het onderhoud. Wandtegels tot het plafond in de douche, elders tot 1,2 meter of alleen achter de wastafel, laten ruimte voor geschilderde muren in een vochtbestendige verf."]),
            ("Sanitair en meubels kiezen",
             ["Sanitair en badkamermeubels worden gekozen op maat van de indeling, niet andersom. X2O Badkamers, met tientallen toonzalen in België en een site op https://www.x2o.be/nl/, biedt baden, douches, kranen, toiletten en badkamermeubels in een ruim aanbod, wat het mogelijk maakt om per zone de juiste maat te vinden en het geheel in de toonzaal te bekijken."]),
        ],
        "partner": {"name": "X2O Badkamers", "url": "https://www.x2o.be/nl/", "anchor": "X2O Badkamers",
                    "blurb": "Baden, douches, kranen, toiletten en badkamermeubels, met toonzalen in heel België."},
    },
    {
        "slug": "kleurplan",
        "nr": "04",
        "fase": "Afwerking",
        "title": "Kleurplan",
        "h1": "Het kleurplan: kleur per ruimte, per vlak en per functie",
        "meta": "Hoe een interieurontwerper een kleurplan opstelt voor een hele woning: verhouding tussen tinten, kleur per vlak, overgangen tussen kamers en de proef op de muur.",
        "intro": "Een kleurplan is een tabel: per ruimte, per vlak een tint en een glansgraad. Het lijkt bureaucratisch, maar het is de reden waarom een ontworpen woning als een geheel voelt en een kamer-voor-kamer geschilderde woning niet. Het plan wordt gemaakt nadat vloer, keuken en badkamer vastliggen, want die materialen bepalen de tinten waar de verf op moet aansluiten.",
        "fiche": [("Fase", "Afwerking, na vloer en vaste inrichting"), ("Resultaat", "Tabel met tint en glansgraad per ruimte en per vlak"), ("Wie", "Ontwerper, schilder"), ("Valkuil", "Kleur kiezen op een staal van vijf centimeter")],
        "steps": [
            ("De verhouding 60-30-10",
             ["Een veelgebruikte verdeling is 60 procent basistint, 30 procent tweede tint en 10 procent accent. De basistint zit op de grote vlakken: muren en plafond. De tweede tint op meubels, gordijnen en een enkele wand. Het accent op accessoires, een deur of een nis. Wie deze verhouding aanhoudt, houdt een kamer rustig, ook met een uitgesproken accentkleur."]),
            ("Kleur per vlak",
             ["Muren, plafond, plinten, deuren en kozijnen zijn aparte vlakken. Alles in dezelfde tint, inclusief plinten en deuren, laat een kamer groter en rustiger ogen. Plinten en deuren in een donkerder tint dan de muur kaderen de kamer af en geven een klassieker beeld. Een plafond lichter dan de muren verhoogt de kamer, een plafond in dezelfde tint als de muren maakt een hoge kamer intiemer."]),
            ("Overgangen tussen kamers",
             ["In een woning met open deuren zijn kamers vanuit elkaar zichtbaar. Een kleurplan legt daarom vast wat naast elkaar komt. Een neutrale gang in een tint die in alle aangrenzende kamers terugkomt, verbindt de woning. Kamers die in elkaar overlopen, delen de basistint en verschillen in de tweede tint. Een harde kleurgrens hoort op een hoek of een deuropening, niet midden op een muur."]),
            ("Licht en proef",
             ["Elke tint wordt getest in de kamer waar ze komt, op een vel van minstens een halve meter, op twee muren, gedurende een dag. Kamers op het noorden krijgen warmere tinten dan de kleurkaart suggereert; kamers op het zuiden verdragen koelere tinten. Kunstlicht wordt in de proef meegenomen: een warmwitte lamp in de avond verandert een koel grijs in een groenig grijs."]),
            ("Verf en kleuradvies",
             ["Levis is het bekendste Belgische verfmerk voor muren en houtwerk, met een site op https://www.levis.info/nl waarop kleurcollecties, een kleurvisualisatie en verfsoorten per toepassing te vinden zijn. Voor een ontwerper die een kleurplan uitwerkt, is een merk met een consistente kleurenwaaier en dezelfde tint in meerdere glansgraden praktisch, omdat muur en houtwerk dan in een tint kunnen zonder kleurverschil."]),
        ],
        "partner": {"name": "Levis", "url": "https://www.levis.info/nl", "anchor": "Levis",
                    "blurb": "Verf en kleurcollecties voor muur, plafond en houtwerk, met kleurvisualisatie."},
    },
    {
        "slug": "lichtplan",
        "nr": "05",
        "fase": "Afwerking",
        "title": "Lichtplan",
        "h1": "Het lichtplan: drie lagen licht in elke ruimte",
        "meta": "Hoe een interieurontwerper een lichtplan maakt: basislicht, functioneel licht en sfeerlicht, lichtkleur, schakelgroepen en de plaats van elk lichtpunt.",
        "intro": "Verlichting wordt in veel woningen als laatste bedacht, wanneer de elektricien al klaar is en er nog een lichtpunt in het midden van het plafond hangt. Een ontwerper tekent het lichtplan op de plattegrond, tegelijk met de meubels, omdat elk lichtpunt bij een functie hoort: lezen, koken, eten, werken, een kunstwerk.",
        "fiche": [("Fase", "Afwerking, voor de elektricien begint"), ("Resultaat", "Lichtplan op de plattegrond, armaturenlijst, schakelplan"), ("Wie", "Ontwerper, elektricien"), ("Valkuil", "Een lichtpunt in het midden van elk plafond en verder niets")],
        "steps": [
            ("Drie lagen",
             ["Basislicht verlicht de ruimte als geheel: inbouwspots, een plafondarmatuur of indirecte verlichting langs een wand. Functioneel licht verlicht een taak: een hanglamp boven de eettafel, spots onder de bovenkasten van de keuken, een leeslamp bij de zetel, een spiegellamp in de badkamer. Sfeerlicht maakt de kamer 's avonds zacht: een tafellamp, een vloerlamp, een wandlamp die omhoog schijnt. Een ruimte met alle drie de lagen, apart schakelbaar, werkt op elk moment van de dag."]),
            ("Lichtkleur en hoeveelheid",
             ["Voor woonruimtes is warmwit licht van 2700 kelvin de norm, voor keuken en badkamer 3000 kelvin, voor een werkplek 3000 tot 4000 kelvin. Alle lampen in een ruimte hebben dezelfde lichtkleur, anders ontstaat een vlekkerig beeld. Een leefruimte vraagt in totaal ongeveer 100 tot 150 lumen per vierkante meter, een keukenwerkblad 300 tot 500 lumen per vierkante meter. Dimbare armaturen zijn het meest flexibel."]),
            ("Plaats en hoogte",
             ["Een hanglamp boven de eettafel hangt met de onderkant op 70 tot 80 centimeter boven het tafelblad. Inbouwspots staan 60 tot 80 centimeter van de muur af om de muur zelf aan te lichten, niet de vloer. Boven een werkblad staan spots recht boven het blad en niet achter de persoon die werkt, om schaduw te vermijden. Een spiegel in de badkamer krijgt licht aan weerszijden of rondom, niet erboven."]),
            ("Schakelen",
             ["Elke laag krijgt een eigen schakelgroep, en een leefruimte krijgt minstens drie groepen. Schakelaars komen bij elke ingang van de kamer en bij het bed. Stopcontacten voor tafel- en vloerlampen worden op de plattegrond getekend waar de lampen komen, liefst geschakeld vanaf de deur, zodat sfeerlicht met een knop aangaat."]),
            ("Armaturen kiezen",
             ["Zodra het lichtplan vastligt, worden de armaturen gekozen. Lampenlicht, met een Belgische webshop op https://www.lampenlicht.be/, biedt hanglampen, vloerlampen, tafellampen, wandlampen en inbouwspots in een breed aanbod en in meerdere stijlen, wat het mogelijk maakt om per laag en per ruimte een passend armatuur te kiezen binnen een samenhangende reeks."]),
        ],
        "partner": {"name": "Lampenlicht", "url": "https://www.lampenlicht.be/", "anchor": "Lampenlicht",
                    "blurb": "Hanglampen, vloerlampen, tafellampen, wandlampen en spots voor elke laag van het lichtplan."},
    },
    {
        "slug": "raamdecoratie",
        "nr": "06",
        "fase": "Afwerking",
        "title": "Raamdecoratie in het ontwerp",
        "h1": "Raamdecoratie in het ontwerp: licht, privacy en akoestiek",
        "meta": "Hoe een interieurontwerper raamdecoratie meeneemt in het plan: functie per raam, keuze tussen gordijn, rolgordijn, jaloezie en shutter, en de bevestiging.",
        "intro": "Raamdecoratie wordt in een ontwerp niet gekozen op uiterlijk maar op functie per raam. Een raam op het zuiden vraagt zonwering, een slaapkamerraam verduistering, een raam aan de straat privacy, en een grote glaswand in een leefruimte vooral akoestische demping. Pas als de functie bekend is, wordt het type gekozen.",
        "fiche": [("Fase", "Afwerking, tegelijk met het kleurplan"), ("Resultaat", "Per raam een functie, een type en een bevestigingswijze"), ("Wie", "Ontwerper, raamdecoratiespecialist"), ("Valkuil", "Rails op het kozijn in plaats van tegen het plafond")],
        "steps": [
            ("Functie per raam",
             ["Op de plattegrond krijgt elk raam een functie. Zonwering voor ramen op het zuiden en westen, verduistering voor slaapkamers, privacy voor ramen aan de straat, en demping voor grote glasvlakken die een kamer hol laten klinken. Een raam kan meerdere functies combineren, en dan wordt vaak gekozen voor een dubbele oplossing: een transparant rolgordijn of vitrage overdag en een dicht gordijn 's avonds."]),
            ("Type per functie",
             ["Gordijnen dempen het best en verzachten een kamer; ze vragen ruimte naast het raam om open te hangen. Rolgordijnen zijn strak en compact en bestaan in transparante, lichtfilterende en verduisterende uitvoering. Jaloezieën regelen het licht in stappen en passen in keuken en badkamer. Shutters zijn een vaste, houten oplossing die de ramen mee ontwerpt. Plissés en duettes passen op kleine en schuine ramen."]),
            ("Bevestiging en aansluiting",
             ["Een ontwerper tekent de bevestiging mee: een gordijnrail in een plafondsleuf, een rolgordijn in de dagkant of op de wand, een shutter in het kozijn. Een plafondsleuf, ingewerkt in een verlaagd plafond, laat gordijnen uit het plafond vallen zonder zichtbare rail. Dat moet voor de plafonneerder begint op tekening staan. Gordijnen hangen tot op de vloer en lopen door tot 20 tot 30 centimeter voorbij het raam aan beide zijden."]),
            ("Stof en tint",
             ["De tint van de raamdecoratie volgt het kleurplan: in de basistint om het raam te laten opgaan in de wand, in de tweede tint om het raam te benadrukken. Linnen en linnenlook passen in een licht, natuurlijk interieur; wol en velours dempen het meest en horen in een warme, rijke ruimte. Voor grote glaswanden wordt vaak een dubbele laag gekozen: een lichte vitrage over de hele breedte en zwaardere gordijnen aan de zijkanten."]),
            ("Op maat bestellen",
             ["Maatwerk is bij raamdecoratie de norm, omdat ramen zelden standaardmaten hebben. Veneta, met een Belgische webshop op https://www.veneta.com/be/nl/, levert gordijnen, rolgordijnen, jaloezieën, plissés en shutters op maat, met gratis stalen en een meetservice aan huis. Voor een ontwerper die per raam een ander type voorschrijft, is een leverancier met het volledige gamma in een reeks tinten praktisch."]),
        ],
        "partner": {"name": "Veneta", "url": "https://www.veneta.com/be/nl/", "anchor": "Veneta",
                    "blurb": "Raamdecoratie op maat: gordijnen, rolgordijnen, jaloezieën, plissés en shutters."},
    },
    {
        "slug": "materialen-en-bouwmarkt",
        "nr": "07",
        "fase": "Uitvoering",
        "title": "Materialen en uitvoering",
        "h1": "Materialen en uitvoering: van materiaalstaat naar bouwmarkt",
        "meta": "Hoe een interieurontwerper een materiaalstaat opstelt en wat de uitvoering vraagt: plaatmateriaal, verf, gereedschap en de volgorde van de werken.",
        "intro": "Tussen het ontwerp en de afgewerkte ruimte zit de uitvoering: de fase waarin een materiaalstaat, dus een lijst van alle materialen met hoeveelheden, wordt omgezet in bestellingen, leveringen en werkdagen. Een ontwerper die de uitvoering begeleidt, houdt de volgorde van de werken en de materiaalstaat naast elkaar, zodat niets te vroeg of te laat op de werf staat.",
        "fiche": [("Fase", "Uitvoering"), ("Resultaat", "Materiaalstaat, planning, bestellijst"), ("Wie", "Ontwerper, aannemer of bewoner die zelf uitvoert"), ("Valkuil", "Afwerkmaterialen leveren voor de ruwbouw droog is")],
        "steps": [
            ("De volgorde van de werken",
             ["Afbraak, ruwbouw, leidingen, pleisterwerk, chape, droogtijd, vloeren en tegels, schilderwerk, keuken en badkamer, meubels, verlichting en raamdecoratie, accessoires. Die volgorde ligt vast omdat elke stap de vorige nodig heeft. Een chape heeft ongeveer een week droogtijd per centimeter dikte; wie daar vloeren op legt voordat de chape droog is, krijgt losliggend parket of schimmel."]),
            ("De materiaalstaat",
             ["Per ruimte en per werk staat in de materiaalstaat wat er nodig is: vierkante meters vloer plus 10 procent snijverlies, liters verf per laag, meters plint, aantal pluggen en schroeven per bevestiging, lijm en kit per tegelvlak. Een ontwerper rekent met de werkelijke maten uit de opmeting, niet met de bruto oppervlakte van de woning. Alles wat te veel besteld wordt, kost opslagruimte; alles wat te weinig besteld wordt, kost een werkdag."]),
            ("Plaatmateriaal en maatwerk",
             ["Kasten op maat, een nis met planken, een zitbank in een erker: dat wordt gemaakt van plaatmateriaal zoals MDF, multiplex of meubelplaat, gezaagd op maat en afgewerkt met verf, fineer of laminaat. MDF is vlak en goed te schilderen maar zwaar en niet vochtbestendig; multiplex is sterker en past in badkamers in een watervaste kwaliteit. Zaagplannen worden op de plattegrond getekend zodat de platen in de bouwmarkt of bij de houthandel op maat gezaagd kunnen worden."]),
            ("Gereedschap en verbruiksmateriaal",
             ["Naast de grote materialen vraagt de uitvoering verbruiksmateriaal: schroeven, pluggen, kit, lijm, tape, schuurpapier, rollers en kwasten, en gereedschap zoals een boormachine, een laserwaterpas, een leidingzoeker en een schroefmachine. Een ontwerper zet dit apart op de lijst, omdat het per stap nodig is en het werk stilvalt als het ontbreekt."]),
            ("De bouwmarkt als leverancier",
             ["Voor plaatmateriaal, gips, verf, gereedschap en verbruiksmateriaal is een bouwmarkt met een webshop en afhaalpunten de meest praktische leverancier tijdens de uitvoering. Brico, met meer dan honderdvijftig winkels in België en een webshop op https://www.brico.be/nl, biedt op maat gezaagd hout en plaatmateriaal, bouwmaterialen, verf en gereedschap, en levert aan huis of in de winkel, wat de planning van de leveringen eenvoudiger maakt."]),
        ],
        "partner": {"name": "Brico", "url": "https://www.brico.be/nl", "anchor": "Brico",
                    "blurb": "Bouwmaterialen, hout op maat, verf en gereedschap, met winkels in heel België."},
    },
    {
        "slug": "montage-en-bevestiging",
        "nr": "08",
        "fase": "Uitvoering",
        "title": "Montage en bevestiging",
        "h1": "Montage en bevestiging: van tekening naar muur",
        "meta": "Hoe een ontwerper de bevestiging van kasten, rails, spiegels en kunst vastlegt: bevestigingsplan, belasting per wandtype, boren en het juiste boortje.",
        "intro": "Alles wat in een ontwerp aan een wand of plafond hangt, bovenkasten, gordijnrails, spiegels, wandmeubels, kunst en verlichting, hangt aan een boorgat. Een ontwerper legt in een bevestigingsplan vast wat waar hangt, hoeveel het weegt en in welk wandtype het komt. Daar volgt het boortje, de plug en de schroef uit.",
        "fiche": [("Fase", "Uitvoering, na schilderwerk"), ("Resultaat", "Bevestigingsplan met hoogte, gewicht en wandtype per element"), ("Wie", "Ontwerper, monteur of bewoner"), ("Valkuil", "Zware bovenkasten aan gipskarton zonder achterliggende constructie")],
        "steps": [
            ("Het bevestigingsplan",
             ["Op een aanzicht per wand staat elk element getekend met de hoogte van de bevestigingspunten. Een bovenkast op 140 centimeter onderkant, een gordijnrail tegen het plafond, een spiegel met het midden op 160 centimeter, een reeks kaders met de bovenrand op een lijn. Per element staat het gewicht erbij en het wandtype uit de opmeting: baksteen, beton, cellenbeton of gipskarton."]),
            ("Belasting per wandtype",
             ["Baksteen en beton dragen met de juiste plug vrijwel elk gewicht. Cellenbeton en snelbouwsteen vragen speciale pluggen en verdelen het gewicht liever over meer punten. Gipskarton draagt met hollewandankers enkele tientallen kilo's per punt, maar zware bovenkasten en wandtoiletten horen in de staanders of aan een vooraf ingebouwde versterking. Wie een gipskartonwand plant, laat daarom op de tekening zetten waar later iets zwaars komt, zodat de plaatser er een houten of metalen versterking achter zet."]),
            ("Het juiste boortje",
             ["Elk wandtype vraagt een ander boortje. Baksteen en beton: een steenboor met hardmetalen punt, klopstand aan, of een boorhamer met SDS-boor voor beton. Cellenbeton en gipskarton: een gewone spiraalboor zonder klopstand. Hout: een houtboor met centreerpunt. Metaal, bijvoorbeeld een stalen profiel of een metalen rail die op maat wordt geboord: een HSS-metaalboor op laag toerental met een druppel olie. De diameter van het boortje is gelijk aan de diameter van de plug; de schroef is een maat kleiner."]),
            ("Netjes werken",
             ["Op een pas geschilderde wand is een uitgebrokkeld boorgat direct zichtbaar. Een stukje schilderstape op de boorplek, boren zonder klopstand voor de eerste millimeters en boorstof opvangen met een stofzuiger houden de wand netjes. Bij een reeks bevestigingen op een lijn wordt een laserwaterpas gebruikt en een papieren sjabloon met de gaten erop geplakt, zodat alle gaten in een keer juist zitten."]),
            ("Boren op maat kopen",
             ["Een bevestigingsplan vraagt boortjes in precies de diameters van de pluggen, en in hout, steen en metaal. In België levert https://www.boorkopen.be/ metaalboren, houtboren, kernboren en toebehoren per diameter uit voorraad, plus batterijen voor laserwaterpassen en leidingzoekers, zodat de uitvoering niet stilvalt op een ontbrekend boortje."]),
        ],
        "partner": {"name": "Boorkopen.be", "url": "https://www.boorkopen.be/", "anchor": "https://www.boorkopen.be/",
                    "blurb": "Metaalboren, houtboren, kernboren en toebehoren per diameter, uit voorraad."},
    },
    {
        "slug": "klokken-in-het-ontwerp",
        "nr": "09",
        "fase": "Inrichting",
        "title": "Klokken in het ontwerp",
        "h1": "Klokken in het ontwerp: een vast punt op de wand",
        "meta": "Waarom een interieurontwerper een klok als vast element tekent: de plaats in de zichtlijn, de verhouding tot wand en meubel, stijl, geluid en bevestiging.",
        "intro": "In een interieurontwerp is een klok geen accessoire dat later wel ergens komt, maar een vast punt op de wand, net als een spiegel of een kunstwerk. Iedereen kijkt er dagelijks naar, dus de klok komt in de zichtlijn vanuit de plek waar het meest gezeten wordt. Een ontwerper tekent de klok op het wandaanzicht, met diameter en hoogte.",
        "fiche": [("Fase", "Inrichting, op het wandaanzicht"), ("Resultaat", "Plaats, diameter en hoogte van de klok per ruimte"), ("Wie", "Ontwerper, bewoner"), ("Valkuil", "Een kleine klok op een grote, verder lege wand")],
        "steps": [
            ("De zichtlijn",
             ["De plek van een klok volgt de zichtlijn: de wand die zichtbaar is vanuit de zetel, vanaf de eettafel of vanuit de keuken tijdens het koken. In een leefruimte is dat vaak de wand boven een dressoir tegenover de zithoek. In een keuken de wand naast het kookgedeelte. In een bureau de wand boven of naast het scherm, niet erachter. In een slaapkamer past een tafelklok op het nachtkastje beter dan een tikkende wandklok."]),
            ("Verhouding tot wand en meubel",
             ["Een klok staat in verhouding tot het vlak waarop hij hangt en het meubel eronder. Boven een dressoir van 180 centimeter past een klok van 60 tot 80 centimeter diameter; de onderrand hangt 15 tot 25 centimeter boven het meubel. Op een lege wand van drie meter is een klok van 30 centimeter verloren; daar hoort minstens 60 centimeter, of een klok als onderdeel van een groep met kaders. Het midden van de wijzerplaat komt op 150 tot 160 centimeter hoogte."]),
            ("Stijl, materiaal en geluid",
             ["De klok volgt het materialenpalet van het ontwerp: zwart metaal in een interieur met zwarte armaturen en kaders, hout in een warm interieur, een minimalistische witte wijzerplaat in een strak interieur. Een klassieke stationsklok of een klok met Romeinse cijfers past in een landelijk of klassiek plan. Het uurwerk hoort in leefruimtes, bureau en slaapkamer stil te zijn; een sweep-uurwerk zonder hoorbaar tikken is dan de keuze."]),
            ("Bevestiging",
             ["Een klok komt op het bevestigingsplan uit hoofdstuk 08 te staan, met gewicht en wandtype. Tot ongeveer twee kilo volstaat een schroef met plug; zwaardere klokken krijgen twee bevestigingspunten of een beugel. In gipskarton is een hollewandplug nodig."]),
            ("Aanbod",
             ["Wie een klok zoekt die in het ontwerp past, vindt op https://www.klokken.be/ een Belgische webshop met meer dan duizend klokken, van moderne en minimalistische modellen tot stationsklokken, staande klokken en tafelklokken, met een aparte collectie wandklokken op https://www.klokken.be/wandklok/. Een breed aanbod in een winkel maakt het eenvoudig om diameter, materiaal en uurwerk te vergelijken tegen de eisen uit het ontwerp."]),
        ],
        "partner": {"name": "Klokken.be", "url": "https://www.klokken.be/", "anchor": "https://www.klokken.be/",
                    "blurb": "Wandklokken, tafelklokken en staande klokken, meer dan duizend modellen uit voorraad."},
    },
    {
        "slug": "styling-en-woonaccessoires",
        "nr": "10",
        "fase": "Inrichting",
        "title": "Styling en woonaccessoires",
        "h1": "Styling en woonaccessoires: de laatste fase van een ontwerp",
        "meta": "Hoe een interieurontwerper een project afrondt met styling: de accessoirelijst, groeperen in oneven aantallen, hoogtes, materialen, tafel en bed.",
        "intro": "Styling is de fase waarin een ontwerp bewoonbaar wordt. De muren zijn geschilderd, de meubels staan, de lampen branden, en toch oogt de ruimte leeg. Wat ontbreekt, zijn de voorwerpen die een ruimte een eigenaar geven: kussens, plaids, tapijten, servies, vazen, boeken, geuren. Een ontwerper maakt daar een lijst van, net als van de meubels, en koopt in die volgorde.",
        "fiche": [("Fase", "Inrichting, de laatste stap"), ("Resultaat", "Accessoirelijst per ruimte, binnen het kleur- en materialenpalet"), ("Wie", "Ontwerper of stylist, bewoner"), ("Valkuil", "Losse aankopen buiten het palet")],
        "steps": [
            ("De accessoirelijst",
             ["Per ruimte staat op de lijst wat nodig is: tapijt met maat, gordijnen als die nog niet in het raamdecoratieplan zaten, kussens met aantal en maat, een plaid, een vaas voor de tafel, kaders voor de wand, opbergmanden, boeken, een kaars of geurstok. Alles binnen het palet van het kleurplan en de materialen van het ontwerp. De lijst voorkomt de losse aankopen die een ontworpen ruimte langzaam terugbrengen tot een gewone ruimte."]),
            ("Groeperen en hoogtes",
             ["Accessoires werken in groepen, niet verspreid. Drie of vijf voorwerpen bij elkaar in verschillende hoogtes, een hoge vaas, een middelhoge schaal, een laag boek, vormen een geheel. Een enkel voorwerp op een leeg dressoir oogt verloren, tien voorwerpen op een rij ogen als een winkel. Op een salontafel volstaan een dienblad met daarop een schaal, een boek en een kaars."]),
            ("Textiel als grootste laag",
             ["Het meeste effect komt van textiel: een tapijt dat de hele zithoek beslaat, kussens in twee formaten en twee structuren, een plaid in de accenttint. Textiel dempt ook geluid, wat in een strak ontwerp met harde vloeren en grote ramen nodig is. Materialen in het textiel volgen het palet: linnen en wol in een natuurlijk interieur, velours en satijn in een rijker interieur."]),
            ("Tafel, bed en bad",
             ["Servies, glaswerk en tafellinnen zijn onderdeel van de styling in een woning met een open keuken. Een dekbedovertrek, kussenslopen en een bedsprei bepalen het beeld van een slaapkamer meer dan de kast. Onder het overtrek telt ook het dekbed zelf: [donzen dekbedden](https://www.bedshop.nl/dekbedden/donzen-dekbedden/) zijn licht en ademend en passen bij een slaapkamer met linnen en wol, synthetische vullingen zijn op hogere temperatuur wasbaar. Handdoeken, een badmat en een zeepdispenser in het palet doen hetzelfde in de badkamer. Een ontwerper neemt die drie plekken mee in de accessoirelijst."]),
            ("Alles bij een leverancier",
             ["Een stylinglijst is eenvoudiger af te werken bij een winkel die tafel, keuken, badkamer, slaapkamer en woonkamer in een aanbod heeft, omdat tinten en materialen dan binnen een collectie op elkaar afgestemd zijn. Salins Home, met een winkel in Heusden-Zolder en een webshop op https://salinshome.be/, verkoopt woonaccessoires en interieurdecoratie voor precies die vijf plekken, met merken als PIP Studio, Heritage en Karaca."]),
        ],
        "partner": {"name": "Salins Home", "url": "https://salinshome.be/", "anchor": "Salins Home",
                    "blurb": "Woonaccessoires en decoratie voor tafel, keuken, badkamer, slaapkamer en woonkamer."},
    },
    {
        "slug": "buitenruimte",
        "nr": "11",
        "fase": "Inrichting",
        "title": "Buitenruimte",
        "h1": "De buitenruimte als verlengstuk van het interieur",
        "meta": "Hoe een interieurontwerper terras en tuin meeneemt in het plan: doorlopende vloeren en tinten, zonering buiten, buitenverlichting, meubels en beplanting.",
        "intro": "Bij een leefruimte met grote glaswanden is de buitenruimte het grootste beeld in de kamer. Een ontwerper neemt terras en tuin daarom mee in het plan, met dezelfde logica als binnen: zonering, materialen, kleur, licht en meubels. Het doel is een terras dat vanuit de zetel als een verlengstuk van de kamer leest.",
        "fiche": [("Fase", "Inrichting, tegelijk met de leefruimte"), ("Resultaat", "Terrasplan met vloer, zones, licht en beplanting"), ("Wie", "Ontwerper, tuinaannemer, bewoner"), ("Valkuil", "Een terras in een ander materiaal en een andere tint dan de binnenvloer")],
        "steps": [
            ("Doorlopen van binnen naar buiten",
             ["Een terrastegel in dezelfde tint en bij voorkeur hetzelfde formaat als de binnenvloer, op hetzelfde niveau en met een smalle dorpel, laat de vloer visueel doorlopen. Buitentegels van 2 centimeter dik in keramiek bestaan in dezelfde reeksen als binnentegels. Ook de tinten van buitenkussens, potten en buitenmeubels komen uit het kleurplan van de kamer ernaast."]),
            ("Zonering buiten",
             ["Een terras krijgt, net als een leefruimte, zones: eten bij de keukendeur, zitten in de zon of juist in de schaduw, een hoek met beplanting die het zicht vanuit de zetel vult. Een loungehoek vraagt ongeveer 3 bij 3 meter, een eettafel voor zes buiten minstens 3 bij 4 meter inclusief stoelen. Windrichting en de stand van de zon in de namiddag en avond bepalen waar de zithoek komt."]),
            ("Buitenverlichting",
             ["Buitenlicht wordt in het lichtplan meegenomen, omdat een verlicht terras 's avonds de kamer groter maakt en een donkere glaswand de kamer juist kleiner. Grondspots bij bomen en planten, een wandlamp bij de deur, lage lichtpunten langs een pad en indirect licht onder een bank volstaan. Alles in dezelfde lichtkleur als binnen, meestal 2700 kelvin, en schakelbaar vanuit de leefruimte."]),
            ("Meubels en beplanting",
             ["Buitenmeubels worden gekozen op weerbestendigheid en op stijl in lijn met binnen: teak of aluminium in een strak interieur, geweven kunststof in een warm interieur. Beplanting vult het beeld: een grote boom of een haag als achterwand, grassen en vaste planten in lagen ervoor, potten in een materiaal dat ook binnen voorkomt."]),
            ("Materialen en tuin",
             ["Voor terrastegels, buitenverlichting, tuinhout, potten en beplanting is een bouwmarkt met een tuinafdeling een praktische leverancier tijdens de uitvoering. Hubo, met meer dan honderdvijftig winkels in België en een webshop op https://www.hubo.be/nl/, biedt bouwmaterialen, tuinhout, buitenverlichting en tuinbenodigdheden, met afhalen in de winkel of levering aan huis."]),
        ],
        "partner": {"name": "Hubo", "url": "https://www.hubo.be/nl/", "anchor": "Hubo",
                    "blurb": "Bouwmaterialen, tuinhout, buitenverlichting en tuinbenodigdheden, winkels in heel België."},
    },
]

OVER = {
    "title": "Over Interieurontwerpersgids.be",
    "meta": "Wat Interieurontwerpersgids.be is: een gids over het werk van de interieurontwerper, opgebouwd als elf hoofdstukken in de volgorde van een ontwerpproces.",
    "paragraphs": [
        "Interieurontwerpersgids.be beschrijft hoe een interieurontwerp tot stand komt, van de eerste briefing tot de laatste vaas op tafel. De gids is geschreven vanuit het vak: de stappen die een interieurontwerper of interieurarchitect zet, de maten en vuistregels die daarbij horen en de documenten die er per fase uit komen.",
        "De gids bestaat uit elf hoofdstukken in de volgorde van een ontwerpproces: voorbereiding, vaste inrichting, afwerking, uitvoering en inrichting. Elk hoofdstuk heeft een fiche met de fase, het resultaat, de betrokkenen en de meest gemaakte fout, gevolgd door het artikel in stappen. Waar dat nuttig is, wordt verwezen naar een leverancier of merk in België dat bij die stap past.",
        "De gids is bedoeld voor wie een ontwerper inschakelt en wil begrijpen wat er gebeurt, en voor wie een ruimte zelf ontwerpt en dat gestructureerd wil aanpakken. Prijzen en tarieven staan niet op deze site; die verschillen per project en per periode.",
        "Opmerkingen en vragen over de inhoud zijn welkom op info@interieurontwerpersgids.be.",
    ],
}


# Blogs van externe auteurs; brontekst staat in blog/<file>.
BLOGS = [
    {"slug": "bouwen-in-amsterdam", "file": "bouwen-in-amsterdam.txt", "datum": "2026-09-25", "datum_nl": "25 september 2026", "datum_kort": "25.09",
     "mt": "Bouwen in Amsterdam: van luxe woningbouw tot duurzaam",
     "meta": "De rol van een aannemer in Amsterdam, luxe woningbouw en maatwerk, restauratie van historische panden, het bouwteam en duurzaam bouwen in de hoofdstad."},
    {"slug": "spiraalkneder-voor-thuisbakkers", "file": "spiraalkneder.txt", "datum": "2026-09-25", "datum_nl": "25 september 2026", "datum_kort": "25.09",
     "mt": "Spiraalkneder voor thuisbakkers: werking en kenmerken",
     "meta": "Wat een spiraalkneder is, hoe het apparaat werkt, welke capaciteit past bij een thuisbakker en het verschil met een standaard keukenmixer."},
    {"slug": "canggu-bali-luxe-wonen-en-investeren", "file": "canggu.txt", "datum": "2026-09-25", "datum_nl": "25 september 2026", "datum_kort": "25.09",
     "mt": "Canggu op Bali: luxe wonen en investeren in villa's",
     "meta": "Luxe wonen in Canggu op Bali: villa's en hun architectuur, rendement en bezettingsgraad, de wijken en wat luxe kopers van een villa verwachten."},
]
